[pytest]
# Задаем какие названия файлов pytest будет считать за тестовые файлы
python_files = test_*.py *_test.py
# Задаем какие названия классов pytest будет считать тестовыми
python_classes = Test*
# Задаем какие названия функция pytest будет считать тестовыми
python_functions = test_*