[pytest]
#Функции которые мы хотим добавлять по умолчанию к запуску тестов. То есть нам больше не придется писать pytest -s -v
addopts = -s -v
# Задаем какие названия файлов pytest будет считать за тестовые файлы
python_files = test_*.py *_test.py
# Задаем какие названия классов pytest будет считать тестовыми
python_classes = Test*
# Задаем какие названия функция pytest будет считать тестовыми
python_functions = test_*
#Регистрируем маркировки что бы не получать варнинги от пайтеста
#Что бы посмотреть документацию по маркировкам надо вписать python -m pytest --markers
markers=
    users: Маркировка для тестов связанных с пользователями
    regression: Маркировка для регрессионных тестов
    authentication: Маркировка для тестов связанных с аутентификацией
    files: Маркировка для тестов связанных с файлами
